# Generated by Django 4.2.5 on 2023-09-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_articulo', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('Fecha_Compra', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
