# Generated by Django 4.2.5 on 2023-09-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderhouse', '0002_articulo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Fecha_Compra',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='Inicio',
        ),
    ]
